INSERT INTO CHARACTERS Values ('Eddard stark','263AC','299AC','Ice',34);
INSERT INTO CHARACTERS Values ('Tywin Lannister','242AC','300AC',NULL,55);
INSERT INTO CHARACTERS Values ('Hot Pie', '290AC', NULL, NULL,12);
INSERT INTO CHARACTERS Values ('Gendyr Baratheon','294AC',NULL,NULL,16);
INSERT INTO CHARACTERS Values ('Daenerys Targaryen','284AC',NULL,'Dragon',24);
INSERT INTO CHARACTERS Values ('Jon Snow','283AC',NULL,'Longclaw',24);
INSERT INTO CHARACTERS Values ('Cersei Lannister', '266AC', NULL, NULL,24);
INSERT INTO CHARACTERS Values ('Gregor Cleagan','303AC',NULL ,'Greatsword',32);
INSERT INTO CHARACTERS Values ('Jaime Lanniser','266AC',NULL,'Widows wail',31);
INSERT INTO CHARACTERS Values ('Arya Stark,','289AC',NULL,'Needle',11);
INSERT INTO CHARACTERS Values ('Sandor Clegane','298AC',NULL ,'Greatsword',27);
INSERT INTO CHARACTERS Values ('Brienne of Tarth','280AC',NULL,'Widows wail',17);
